[server]
# Server configuration
port = 8501
address = "0.0.0.0"  # Docker needs to listen on all interfaces
headless = true      # Headless mode for Docker
enableCORS = false
enableXsrfProtection = false

# File watcher settings - work around file-locking on Windows
fileWatcherType = "none"
runOnSave = false

[browser]
# Browser settings
gatherUsageStats = false

[logger]
# Logging config
level = "info"

[global]
# Global settings
developmentMode = false

[theme]
# Theme settings
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"